---

# Create SA 

- name: Create service account via manifest
  kubernetes.core.k8s:
    kubeconfig: /home/svc_ansible/kubeconfig
    state: present
    definition: "{{ lookup('template', 'templates/service_account.yaml.j2') }}"
  tags: create_sa

# Create Secret to generate token

- name: Create Secret for SA token
  kubernetes.core.k8s:
    kubeconfig: /home/svc_ansible/kubeconfig
    state: present
    definition: "{{ lookup('template', 'templates/sa_secret_token.yaml.j2') }}"
  tags: create_token
