---
- name: Create Namespace for cert-manager
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
    host: "{{ k8s_api_host }}"
    api_key: "{{ k8s_sa_token }}"
    validate_certs: false

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    chart_ref: "{{ chart_ref }}"
    chart_version: "{{ chart_version }}"
    values: "{{ lookup('template', 'cert-manager-values.yaml.j2') | from_yaml }}"
    host: "{{ k8s_api_host }}"
    api_key: "{{ k8s_sa_token }}" 
    validate_certs: false


# Create ClusterIssuer

# Patch Ingress Controller
  